### ISSUE TITLE
Nan values in .npz files

### ISSUE THREAD

**Issue by Alissa13777** [nansencenter/satellite-data-pipeline#16]
When running the training on the .npz files I have got the loss function equal to nan. When debugging, I found that there a nan values in the .npz files (in the matrixes for 'nersc_sar_primary' and 'nersc_sar_secondary'). 
I have run  the python train_model.py -o /fold2  -bs 4 -p 0.8 -see -sft on the .npz files extracted from the following .nc files:
- 20180410T084537_S1B_AMSR2_Icechart-Greenland-SouthEast.nc
- 20190404T201246_S1A_AMSR2_Icechart-Greenland-SouthEast.nc
- 20190423T200433_S1A_AMSR2_Icechart-Greenland-SouthEast.nc
- 20190509T081206_S1A_AMSR2_Icechart-Greenland-CentralEast.nc
- 20190509T081306_S1A_AMSR2_Icechart-Greenland-CentralEast.nc
- 20190519T194808_S1A_AMSR2_Icechart-Greenland-SouthEast.nc
- 20190519T194908_S1A_AMSR2_Icechart-Greenland-SouthEast.nc
- 20190523T200352_S1B_AMSR2_Icechart-Greenland-SouthEast.nc

To find the nan values, I have run a Python script that stocks the different values of each file and then did a CTRL+F. 
In the Method 2 of the python script (https://github.com/Alissa13777/Internship_NERSC_CNN_IceTypes), one can see the file in which there are nan values in the shell.

**Comment by azamifarda** [comment]
@Alissa13777 solved with #18

**Comment by azamifarda** [comment]
Not completely solved by #18.

**Comment by Alissa13777** [comment]
Solved the issue with a filtering script. (nan values also in btemp_69h and btemp_69v files). Putting the script on personal github.

**Comment by Alissa13777** [comment]
Mask not working properly in archive.py in get_the_mask_of_amsr2_data(self, amsr_labels, fil) function (line 297). There are nan values after the mask is calculated and applied.

**Comment by azamifarda** [comment]
@Alissa13777 
Have you run the code this what is inside the test branch? I have fixed both two bugs previous week in that PR.

**Comment by azamifarda** [comment]
If not, run the building with the new code. Could you please run this script in a seperate file and screenshot the resutl of your execution?
```python
import os
import numpy as np

file_list = os.listdir("output")
for file_ in file_list:
    if file_.endswith('.npz'):
        v=np.load(os.path.join("output",file_))
        for variable in v.files:
            print(">>>>>>>>>>>variable:", variable)
            assert None not in v[variable]
```
I have run it and everything is correct as shown below:
![image](https://user-images.githubusercontent.com/62345618/121202811-e134e100-c875-11eb-913c-05913ddca6fb.png)

**Comment by azamifarda** [comment]
We have tests for making sure that the function works properly. Have at these two tests:
1.
https://github.com/nansencenter/satellite-data-pipeline/blob/b1364be823b4e2cd25aadaf6ad871c7a03656c95/asip_v2/tests/test_archive.py#L305

2.
https://github.com/nansencenter/satellite-data-pipeline/blob/b1364be823b4e2cd25aadaf6ad871c7a03656c95/asip_v2/tests/test_archive.py#L316

**Comment by akorosov** [comment]
Confirmed as solved by Alissa
